### ISSUE TITLE
ENV variable to force validation to suceed

### ISSUE THREAD

**Issue by unixcharles** [letsencrypt/pebble#106]
Often time, the validation process itself is outside the scope of the client.

It would be great if there was a way to skip the validation for testing purpose for this type of client.

Something like `PEBBLE_VERIFICATION_ALWAYS_SUCCEED=1`.

**Comment by cpu** [comment]
@unixcharles Does the implementation in https://github.com/letsencrypt/pebble/pull/117 meet your needs? You might want to pair it with `PEBBLE_VA_NOSLEEP`.

**Comment by unixcharles** [comment]
Perfect! Thanks
