### ISSUE TITLE
Implement account deactivation

### ISSUE THREAD

**Issue by rmbolger** [letsencrypt/pebble#108]
Per https://tools.ietf.org/html/draft-ietf-acme-acme-10#section-7.3.7

> A client can deactivate an account by posting a signed update to the
   server with a status field of "deactivated."  Clients may wish to do
   this when the account key is compromised or decommissioned.

Pebble currently seems to ignore an account update with `{"status":"deactivated"}`. The resulting account object returned still has `"status":"valid"`.

I realize this likely falls under the category of stuff like revocation and account key rollover that's not implemented yet. I just wanted to throw it out there for tracking.

**Comment by cpu** [comment]
@rmbolger Thanks for opening this tracking issue. Agreed that Pebble should eventually support this feature :-)
