### ISSUE TITLE
Setting header 'kid' to account ID rather than account URL works

### ISSUE THREAD

**Issue by rmbolger** [letsencrypt/pebble#109]
Per https://tools.ietf.org/html/draft-ietf-acme-acme-10#section-6.2

> For all other requests, the request is signed using an existing
account and there MUST be a "kid" field.  This field MUST contain the
account URL received by POSTing to the newAccount resource.

This probably gets filed as unintentional feature, but technically a bug for strict adherence to the current draft 10 spec.

Pebble *(and Boulder)* currently includes an `ID` field in Account object output as well as the `Location` header value with full Account URL. For example, `"ID": "abcd1234"` and `https://localhost:14000/my-account/abcd1234`.

Subsequent requests that require a `kid` value in the header will accept the raw ID value `"kid":"abcd1234"` in addition to the URL which is technically wrong. It seems to be because the code blindly trims the account prefix from whatever kid was sent before checking it.
https://github.com/letsencrypt/pebble/blob/cae1c3522ee7a4871550f4ff9378677e06a4cdf7/wfe/wfe.go#L403-L405

Ironically, I only figured this out after realizing that my client code was wrong and then wondering why it hadn't been throwing an error.

**Comment by cpu** [comment]
> It seems to be because the code blindly trims the account prefix from whatever kid was sent before checking it.

Good catch - this should be fixed in Pebble to reject a KID that doesn't exactly match expected. :+1:

**Comment by rmbolger** [comment]
Happy to help.

**Comment by cpu** [comment]
>  this should be fixed in Pebble to reject a KID that doesn't exactly match expected.

Implemented in #125.
