### ISSUE TITLE
Orders with unvalidated and expired authorizations remain in state 'pending'

### ISSUE THREAD

**Issue by rmbolger** [letsencrypt/pebble#110]
Pebble currently appears to set the expires field on a newly created order to 24 hours past when the order was created. The associated authorizations appear to get 1 hour before they expire. No problem there.

However, if the 1 hour time limit elapses on the authorizations without being validated, they seem to remain in a pending state forever. But you get an "Authorization expired" error if you try to POST to a challenge's URL.

I would think that querying the authorization's status returns "invalid" once the expiration time has been reached. I would think that also then sets the order status to "invalid" as well.

Have I misread the spirit of the spec? Or is there a way to generate new authorizations for an existing order?

**Comment by rmbolger** [comment]
Also related to this issue is that if an authorization gets set to 'invalid', the order status still has status 'pending'. Whereas with Boulder, the order status also switches to 'invalid'. Even if all authorizations are 'invalid', the order status remains 'pending'.

**Comment by cpu** [comment]
@rmbolger You're correct on the expected behaviour here. These are some corner cases we caught in Boulder that haven't been backported to Pebble. Apologies!

We should be calculating the order's status based on the associated authorization status instead of using a stored field.
