### ISSUE TITLE
Attempts to clear contact on an account don't succeed and don't throw error.

### ISSUE THREAD

**Issue by rmbolger** [letsencrypt/pebble#114]
I'm trying to implement a feature in my client to remove an account's contact information.

Per https://tools.ietf.org/html/draft-ietf-acme-acme-11#section-7.3.2

> If the client wishes to update this information in the future, it
   sends a POST request with updated information to the account URL.
   The server MUST ignore any updates to the "orders" field or any other
   fields it does not recognize.  If the server accepts the update, it
   MUST return a response with a 200 (OK) status code and the resulting
   account object.

I've tried two different methods to empty the contact field. Within the payload of the request: 

- `"contact":null`
- `"contact":[]`

Both of these return a 200 (OK) status as if they were accepted. But the resulting account object still has the old value for the contact field.

I tried testing against the Boulder v2 staging server as well. `"contact":[]` works and does clear the field. `"contact":null` works the same as Pebble and doesn't modify the account or throw an error.

It would be awesome if both methods worked. But I can settle for only `"contact":[]` working. Though, perhaps it would be more appropriate to generate an error on `"contact":null` in that case?

**Comment by cpu** [comment]
>  I tried testing against the Boulder v2 staging server as well. "contact":[] works and does clear the field. 

Yup! Pebble should be doing this :+1: Good catch, thanks @rmbolger 

Supporting `"contact": null` is tricky with the Go JSON package. I think sending an empty contact list is the clearest communication of the intent to set the contacts to nothing.
