### ISSUE TITLE
Wildcard orders being rejected with "illegal character: '*'" error

### ISSUE THREAD

**Issue by rmbolger** [letsencrypt/pebble#126]
I believe PR #122 accidentally introduced a bug that now rejects wildcard domain identifiers in new order requests.

https://github.com/letsencrypt/pebble/blob/2462e275194e207253e4cfd407578dca61bc4cf0/wfe/wfe.go#L767-L772

https://github.com/letsencrypt/pebble/blob/2462e275194e207253e4cfd407578dca61bc4cf0/wfe/wfe.go#L811-L815

Should the `*` character be added to the allowed list in `isDNSCharacter`?

**Comment by cpu** [comment]
Good catch, thanks! I based #126 on Boulder's `PA.WillingToIssu`e but totally forgot that wildcard support is predicated on `PA.WillingToIssueWildcard` and should have been considered for Pebble.

**Comment by cpu** [comment]
Fixed in master with c5ebb21. Thanks @rmbolger !
