### ISSUE TITLE
Fix some issues in Dockerfile

### ISSUE THREAD

**Issue by jsha** [letsencrypt/pebble#144]
I had some late-breaking feedback on the PR adding a Dockerfile: https://github.com/letsencrypt/pebble/pull/143#pullrequestreview-134779715.

This issue is to track implementation of that feedback.

**Comment by ldez** [comment]
Ok I'll fix that

**Comment by ldez** [comment]
> This should probably be `CMD` rather than `ENTRYPOINT`. The difference: If you pass an alternate command to docker run, it gets passed as an argument to `ENTRYPOINT`, but it overrides `CMD`. So for instance if you wanted to run bash in the context of this container it would not work right due to the `ENTRYPOINT`.

https://github.com/letsencrypt/pebble/pull/143#discussion_r200457538

There is some others differences:
- `CMD`
```bash
# works
docker run letsencrypt/pebble
# Fail
docker run letsencrypt/pebble -dnsserver 10.10.10.10:5053
# works
docker run letsencrypt/pebble pebble -dnsserver 10.10.10.10:5053
# works
docker run -it  letsencrypt/pebble /bin/sh
```

- `ENTRYPOINT`
```bash
# works
docker run letsencrypt/pebble
# works
docker run letsencrypt/pebble -dnsserver 10.10.10.10:5053
# fail
docker run letsencrypt/pebble pebble -dnsserver 10.10.10.10:5053
# fail
docker run -it  letsencrypt/pebble /bin/sh
```

@jsha Could you confirm that you want the `CMD` behavior?

**Comment by jsha** [comment]
Good point about the subtle differences! It is indeed important that people be able to run with arguments. However, I think this form:

```
docker run letsencrypt/pebble pebble -dnsserver 10.10.10.10:5053
```

is fine even though it's slightly more typing. I've found that having an entrypoint can make it difficult to debug things about containers. It's very helpful to be able to run `docker run -it letsencrypt/pebble bash`.

**Comment by felixfontein** [comment]
@jsha Is there any advantage (except in the case of when `pebble` won't start, or will instantly terminate for some reason) over using `docker run -it <your-container-name> /bin/bash` for an already running container to investigate?

**Comment by jsha** [comment]
> except in the case of when pebble won't start, or will instantly terminate for some reason

In my personal experience, most of the cases when I need to debug an image are when the thing contained in that image won't start for some reason. That said, I didn't know you could run a shell inside an already running container. That's really useful, thanks for letting me know!

**Comment by felixfontein** [comment]
For non-starting containers, there's of course always the work-around by creating a new image derived from the non-working one whose only difference is that it overrides `ENTRYPOINT`. It's quite annoying to do that, but it works ;-)
I think the trade-off of using `ENTRYPOINT` over `CMD` (easy usage by default, and annoying work-around if `pebble` doesn't start) is usually worth it.
