### ISSUE TITLE
Version numbers/identifiers for Docker image tags

### ISSUE THREAD

**Issue by felixfontein** [letsencrypt/pebble#146]
It would be nice if there would be some kind of version numbers or identifiers for Pebble which can be used to identify specific versions, for example for tags in the official Pebble repository (https://hub.docker.com/r/letsencrypt/pebble/tags/). Having only latest is not so useful if you want to target a specific version :-)

Ideas for version identifiers:
 * commit IDs (the ones from `master`) (I'm using that right now for a [ACME testing container](https://github.com/felixfontein/ansible-acme-test/));
 * dates (version is built from the latest commit to `master` on that day);
 * some integer or "regular" version number (which someone has to increment for every commit/set of commits which should define a new version). This requires manual work (or some clever scripting, with storing the version number somewhere).

I think I'd prefer the first solution, since it is the simplest to implement. Any suggestions/thoughts/ideas?

**Comment by cpu** [comment]
We use the second date-based option for Boulder's docker image tags. I'd be slightly in favour of that for consistency's sake.

**Comment by felixfontein** [comment]
Considering the amount of commits Pebble has, this is essentially equivalent to `master`'s `HEAD` ;-)

Would every day get a new date tag, or would only days when new commits are added get a new date tag?

**Comment by cpu** [comment]
> or would only days when new commits are added get a new date tag?

Only days where new commits were added. I think Pebble's commit volume is pretty low.

**Comment by cpu** [comment]
I haven't been able to figure out how to get Dockerhub autobuilds working for a public repo in the Let's Encrypt organization. I must be missing something silly but it only ever shows me repositories from my own Github account.

In the meantime I pushed a `letsencrypt/pebble:2018-07-20` tag to Dockerhub for the current master (dac33b8b8c92687b23d275ad2383daf18bc37157)

**Comment by ldez** [comment]
@cpu You need to create the repo like that:
![auto-build](https://user-images.githubusercontent.com/5674651/43015643-64df8486-8c3f-11e8-903c-2eab70146d80.png)

**Comment by cpu** [comment]
@ldez That's the section of DockerHub I've been interacting with (following the instructions here: https://docs.docker.com/docker-hub/github/)

After clicking the "Create Automated Build" I land on this screen:
![autobuild 1](https://user-images.githubusercontent.com/292650/43016097-c02c1810-8c1f-11e8-9889-22ae3276f826.png)

Choosing the Github option then brings me to a page where I can see my own linked Github account's repositories:

![autobuild 2](https://user-images.githubusercontent.com/292650/43016115-cafb8622-8c1f-11e8-89cb-af52b3283c3e.png)

Despite being a member of the Let's Encrypt organization (I seem to have admin rights on our org's repos in Dockerhub) it doesn't show anything but my own personal repositories. E.g. I can't select this github.com/letsencrypt/pebble repository.

Am I doing something silly? The DockerHub "LetsEncrypt" organization predates me. Maybe there are account credentials for it that could be used to log in to the dockerhub that I should be using instead?

**Comment by cpu** [comment]
Aha! I read the docs a second time and I think this might be the catch I'm missing: https://docs.docker.com/docker-hub/github/#github-organizations 

I'll investigate and see if our GH org admin needs to activate this.

**Comment by ldez** [comment]
Docker hub have a bug to refresh repositories.
Try to logout/login.

**Comment by ldez** [comment]
Sorry try to `Unlink Github` -> `link to Github` for Docker account.

**Comment by cpu** [comment]
@ldez I'm 100% stumped. I've unlinked and relinked my Github several times (and also logged in/out of Dockerhub) with no results.

I added the "Docker" service to the repo (despite the deprecation warnings), and it shows a "green" status: 
![integration](https://user-images.githubusercontent.com/292650/43078804-77d49e52-8e59-11e8-8d29-15893539e627.png)

I also had a Github org admin for the "letsencrypt" org check the org perms and they indicated there doesn't seem to be anything missing.

Despite all of the above I still can **only** see my own repositories when following the instructions for creating an auto-build with Dockerhub. Pretty frustrating!

I'm open to suggestions. I must be missing something....

**Comment by ldez** [comment]
As you see I can access to the repositories of an organization.
![dockerhub-org](https://user-images.githubusercontent.com/5674651/43080334-0dc10020-8e7f-11e8-88cc-df08993489b8.png)

To be sure:
- From Docker Hub: `Unlink Github` -> `link to Github`

Do you have the "good" rights on the https://hub.docker.com/u/letsencrypt/ organization?

**Comment by cpu** [comment]
> As you see I can access to the repositories of an organization.

Very strange. I see what you mean but the Let's Encrypt organization doesn't show up for me in "Users/Organizations"

> To be sure: From Docker Hub: Unlink Github -> link to Github

Yup! Tried that several times now, also making sure to revoke from the Github side.

> Do you have the "good" rights on the https://hub.docker.com/u/letsencrypt/ organization?

As far as I know. I'm able to edit the DockerHub organization settings. I was also able to create the "letsencrypt/pebble" repository: https://hub.docker.com/r/letsencrypt/pebble/

**Comment by cpu** [comment]
I haven't had a chance to try and take another crack at auto-builds. In the meantime I'll push new tags when master changes manually :sob:

**Comment by ldez** [comment]
I agree with @shred and I will also use `latest`.

So your choice will be best :smile_cat:

**Comment by ldez** [comment]
I forgot something:
- in Lego, I will use `latest` because I want to detect new features/fixes as soon as possible
- in Traefik, I will use a "stable" version, because I don't want to failed on features/fixes that are not available in the LE production

**Comment by jsha** [comment]
Semver is great!

**Comment by ldez** [comment]
So I propose to update my PR like that:

- latest: the latest tagged version
- tag: each tag have an image
- no image per commit hash

Are you agree?

**Comment by cpu** [comment]
@ldez Yes that sounds great.

It sounds like everyone is comfortable with semver so we'll go that direction for making tags/releases :+1: Thanks!

**Comment by cpu** [comment]
This is all wrapped up now :tada: I released a `v1.0.0` and a `v1.0.1` today (https://github.com/letsencrypt/pebble/releases/). There's a `latest` tag in Dockerhub for both `pebble` and `pebble-challtestsrv` as well as images for the v1.0.1 release tag (I will backfill v1.0.0 images later).
