### ISSUE TITLE
Support IP address identifiers

### ISSUE THREAD

**Issue by cpu** [letsencrypt/pebble#161]
Pebble should support IP type identifiers in addition to DNS type identifiers by implementing [draft-ietf-acme-ip-04](https://tools.ietf.org/html/draft-ietf-acme-ip-04).

This will involve:

- [x] - creating a new identifier type constant in `acme/common.go`
- [x] - updating the WFE to allow IP type identifiers in newOrder requests
- [x] - updating the WFE to validate the IP identifiers
- [x] - updating the TLS-ALP-01 implementation to properly handle IP address identifiers
- [x] - updating the HTTP-01 implementation to properly handle IP address identifiers
- [x] - updating the DNS-01 implementation to forbid IP address identifiers
- [x] - updating the CA to issue certificates for orders with IP address identifiers using appropriate SAN entries with iPAddress type
- [x] - ??? I'm probably forgetting something!

This will be the first time we've supported an identifier type other than DNS and we should be doubly cautious that we don't miss any details or assumptions in the existing code.

**Comment by orangepizza** [comment]
I made I_think_this_works version, can't find client that support pebble and easy enough to mass with
it's compiled and tested for signs cert wih normal domains, can checked WFE parts with modified client, but couldn't make the clients work with actual CSR with IP Address. , but when csr passed with shortcut (with some hack), it will sign it properlly
from checklists:
[pebble.zip](https://github.com/letsencrypt/pebble/files/2939608/pebble.zip)

 

- [x]  creating a new identifier type constant in acme/common.go : defined as "ip" (all small)

- [x] updating the WFE to allow IP type identifiers in newOrder requests done

- [x] updating the WFE to validate the IP identifiers done, and it still rejects if it's 

- [ ] updating the TLS-ALP-01 implementation to properly handle IP address identifiers not yet, it can't validate by this 


- [ ] HTTP-01 : handles 
- [x] DNS-01 : blocked as enabledchallengs at wfe
- [x] CA : 

- [ ]

**Comment by ffdybuster** [comment]
@orangepizza why not create a PR for this here and mark it as WIP? That way it is easier for others to look at and comment your code.

I can try your code out with my client; I've added experimental support for IP identifiers a couple of days ago, then we can see whether/how it works.

**Comment by shred** [comment]
IP identifiers are supported (and at least unit tested) by my client, too. I could give it a try as well.

**Comment by ffdybuster** [comment]
PR is in #221.

**Comment by cpu** [comment]
Thanks everyone! It would certainly be useful to hear about any interop testing you folks manage to do. Please share your experience in this thread.

**Comment by shred** [comment]
I could successfully create an IP based certificate via http-01 using acme4j. :+1:

**Comment by felixfontein** [comment]
Sorry, took me a bit longer to really try this out. I've now managed to get a certificate for a IPv4 address (`127.0.0.1`) and a IPv6 address (`::1`) issued!

**Comment by felixfontein** [comment]
I've now also managed to get a certificate for `127.0.0.1` with TLS-ALPN-01 validation! \o/

(I can't get one for `::1` since apparently Python's `socketserver` doesn't work for IPv6...)

**Comment by cpu** [comment]
Implemented in https://github.com/letsencrypt/pebble/commit/bc4da68d49d78a38bfea869d38faadc8c714654c thanks to @orangepizza :tada: :clinking_glasses:
