### ISSUE TITLE
Advertise important urls at program startup

### ISSUE THREAD

**Issue by m-adler** [letsencrypt/pebble#165]
When pebble is started, the URL is displayed where the server can be reached.
It would also be helpful to output the URL to the endpoint directory (https://localhost:14000/dir).
The directory URL should also be documented in the README.

It may also be useful to output the CA Root CertificateURL (https://localhost:14000/root) at startup.

**Comment by cpu** [comment]
Thanks for the suggestion @m-adler - I've put up a PR to do as you requested in https://github.com/letsencrypt/pebble/pull/169
