### ISSUE TITLE
Strict mode not enforcing Post-As-Get for certificate download

### ISSUE THREAD

**Issue by rmbolger** [letsencrypt/pebble#175]
Per the community thread here:
https://community.letsencrypt.org/t/any-update-on-gets-posts-conversation/73139/10

I believe Pebble in Strict mode should be rejecting GET requests for certificates in favor of Post-As-Get requests. But it currently does not.

**Comment by ffdybuster** [comment]
See #174.

**Comment by rmbolger** [comment]
Whoops. Should have looked in PRs as well as Issues. My bad.

**Comment by ffdybuster** [comment]
No problem. At least now there's an issue to close when that PR gets merged ;-)

**Comment by cpu** [comment]
I'll bump someone to review #174 today. Thanks!
