### ISSUE TITLE
pebble-challtestsrv: dns-01 endpoint not found

### ISSUE THREAD

**Issue by shred** [letsencrypt/pebble#188]
In the pebble-challtestsrv README, the endpoint for adding a DNS-01 challenge response is documented as `http://localhost:8055/add-txt`. In the `main.go` however, the controller is registered as `/set-txt`.

I would send a PR, but both names make sense, so I don't know if the documentation or the code is wrong. :wink:

**Comment by shred** [comment]
The same for documented `http://localhost:8055/clear-tlsalpn01`, but the controller is registered as `/del-tlsalpn01`.

**Comment by shred** [comment]
The DNS-01 part states that for a challenge response to `_acme-challenge.test-host.letsencrypt.org`, this example JSON can be used:

```
'{"host":"_acme-challenge.test-host.letsencrypt.org", "value": "foo"}'
```

However, `host` seems to require a trailing period:

```
'{"host":"_acme-challenge.test-host.letsencrypt.org.", "value": "foo"}'
```

Again, I don't know if the documentation is wrong, or if challtestsrv should internally append the required period.

**Comment by jsha** [comment]
Let's go with updates to the documentation, since there are already integration tests that rely on the code behavior. Thanks for pointing these out!
