### ISSUE TITLE
VA: Ignore certificate errors in HTTP-01 validation

### ISSUE THREAD

**Issue by cpu** [letsencrypt/pebble#195]
I mistakenly believed the Pebble VA implemented roughly the same redirect processing as Boulder but that is not the case.

* The VA's simple `fetchHTTP` doesn't use a transport with `InsecureSkipVerify` set:
https://github.com/letsencrypt/pebble/blob/2132a88193fdf0d7c0d93c33fce61db43d630fd4/va/va.go#L487-L501
* The VA doesn't implement a `CheckRedirect` function on the `http.Client` like Boulder so we don't restrict the ports/protocols that can be used in a redirect target.

At the minimum `fetchHTTP` should use a transport with `InsecureSkipVerify: true` to ignore certificate errors on HTTPS redirects.

It's not completely clear to me whether there's value in implementing the restricted redirect handling. We should confirm that the VA follows redirects but I think the port/protocol restrictions are perhaps closer to CA policy than ACME spec requirements.

**Comment by jsha** [comment]
Yeah, I agree we should keep the redirect logic in Pebble simple.
