### ISSUE TITLE
JWS header parameter 'url' required.

### ISSUE THREAD

**Issue by odedpriva** [letsencrypt/pebble#20]
Hi, 

I'm trying to use pebble with certbot and dehydrated clients but I'm getting the following error:

**with certbot :**  
```
certbot --config-dir ~/letsencrypt --work-dir ~/letsnecrypt --logs-dir ~/letsencrypt  --server "${SERVER:-http://localhost:14000/dir}" --no-verify-ssl --tls-sni-01-port 5001 --http-01-port 5002 --manual-public-ip-logging-ok --non-interactive --no-redirect  --agree-tos --register-unsafely-without-email  --debug certonly -a standalone -d example.com

Error: urn:ietf:params:acme:error:malformedRequest :: JWS header parameter 'url' required.
```

**with dehydrated** using nginx lua 

```
 + ERROR: An error occurred while sending post-request to http://pebble:14000/sign-me-up (Status 400)

Details:
{
   "type": "urn:ietf:params:acme:error:malformedRequest",
   "detail": "JWS header parameter 'url' required.",
   "status": 400
}

rm: cannot remove '/etc/resty-auto-ssl/letsencrypt/domains.txt': No such file or directory
```

I have downloaded pebble today.  
what is missing in my request ?

**Comment by cpu** [comment]
@odedpriva As of today neither certbot nor dehydrated support the ACME protocol version that Pebble implements. I wouldn't expect they would work out-of-box with Pebble and this error about a missing JWS header parameter is one instance of why. These clients have [implemented an ACME spec divergence from Boulder](https://github.com/letsencrypt/boulder/blob/master/docs/acme-divergences.md#section-541).

**Comment by odedpriva** [comment]
I'm looking for an internal ACME server for local development and staging environment. 
We have a Docker based development environment and I would like to integrate an ACME service as part of it. 

Boulder seems too much for our use case.

**Comment by cpu** [comment]
Hi @odedpriva,

Thanks for the explanation! That makes sense and I think Pebble will be a good fit for that setup one day but it's a little bit premature at this point since there are no compatible clients.

If you're interested in testing clients against an ACME server your best bet for the short term will be following Boulder's quick start guide, even if its a heavier weight option than you were hoping.

**Comment by odedpriva** [comment]
@cpu thanks. I will follow up on Pebble with anticipation.
