### ISSUE TITLE
Switch Travis Certbot checkout to master after keyAuthorization changed

### ISSUE THREAD

**Issue by jsha** [letsencrypt/pebble#204]
Right now we check out a branch of Certbot patched to remove "keyAuthorization," for compatibility with Pebble's rejection of that field. Once Certbot stops sending keyAuthorization by default we should switch back to master.

**Comment by adferrand** [comment]
For the record, I added also the `no-keyauthorization-windows` branch on Certbot repo after the existing `no-keyauthorization`. It contains specifics to run Certbot on Windows with patches that will be integrated in the next days.

I will update accordingly.
