### ISSUE TITLE
Design of Windows CI/CD pipeline for Pebble

### ISSUE THREAD

**Issue by adferrand** [letsencrypt/pebble#208]
The general idea of this design proposition, is to setup an AppVeyor CI/CD pipeline that ultimately publish on Docker Hub a Windows Container for Pebble, and another one for Pebble-Challtestsrv.

Indeed my recent tests to build Certbot on Windows showed that Pebble can run on Windows out-of-the-box, and so is a suitable integration tests ACME CA server for this platform. The preferred way to distribute the software would be Windows Containers available on Docker Hub side by side to their Linux counterparts.

I see two general approaches for the AppVeyor CI:
1) Create an equivalent pipeline to Travis CI for Linux
2) Focus only on the Docker Hub publication

For 1), it means to translate each step of the Travis CI/CD pipeline to the AppVeyor CI/CD one:
* setup hosts and environment variables
* clone Certbot, setup its venv, enable it
* go install pebble and start the generated binary
* run chisel2.py
* build from source the docker, and publish it

The way AppVeyor is configured is really close to the Travis approach, consuming a `appveyor.yml` YAML file with typical steps of run, build, test and deploy. So the technology allows to follow the same general approach. In the details, apart from Go which is built to be cross-platform out-of-the-box:
* Certbot is already working on Windows, on a satisfactory test-grade level (almost all unit tests are passing, in `acme` module is already fully compatible)
* from what I see, `chisel2.py` has no platform specific code
* Docker is available and running on standard AppVeyor Windows platform

On the cons, the full build logic needs to be maintained on both AppVeyor and Travis. On the pros, Pebble is fully tested on Windows before its publication to Docker Hub.

For 2), the idea would be to first poll the relevant build status from Travis, using its API (see https://docs.travis-ci.com/user/developer/#api-v3). When the final status (succeed/failed) is obtained, AppVeyor proceed this way:
* in case of Travis build failure, the AppVeyor build is failed
* in case of Travis build succeed, AppVeyor build and publish the Windows Docker, in a really similar way to the last step of the solution 1).

On the cons, Pebble is not tested on Windows, only relying on the results obtained on Linux. On the pros, AppVeyor config contains less logic, and does not need to be maintained in parallel to the Travis on. Also, the tests are relying on Certbot for Linux, which is at a production-grade level.

I prefer personnally 1) for the Windows testability, but I wanted to propose an alternative with less AppVeyor knowledge commitment.

As last words, you can see on by fork a running example of AppVeyor building and pushing Pebble + Pebble-Challtestsrv Windows Docker upon GIT push, and operable relevant Dockerfiles for Windows.

@jsha, @cpu, I am open and available for discussions!

**Comment by cpu** [comment]
Thanks for the detailed proposal @adferrand! 

> On the cons, the full build logic needs to be maintained on both AppVeyor and Travis. On the pros, Pebble is fully tested on Windows before its publication to Docker Hub.

I think the duplication will be fairly minimal and the advantage of a fully tested Windows build sounds appealing enough to offset the downside IMO. I would be +1 to pursuing this path as opposed to relying on the Linux Travis build status.
