### ISSUE TITLE
strict: reject JWS bodies that include "resource" field.

### ISSUE THREAD

**Issue by cpu** [letsencrypt/pebble#245]
Some legacy ACME v1 clients may end up sending a `"resource"` field with the request URL in ACME v2 / RFC 8555 settings (e.g. [Cerbot](https://github.com/certbot/certbot/issues/5708)). 

Pebble should reject these requests in `-strict` mode. Yes: the "resource" field isn't required/specified in RFC 8555 JWS bodies because the full request URL is in the JWS protected headers.

**Comment by tammersaleh** [comment]
I'm attempting to make use of the `acme` python library (part of Certbot), using the v2 ACME specification.  When running `pebble -strict`, it's triggering this error.  Just to clarify, does that mean that my application won't be v2 compliant (as v1 is being deprecated), or is this normal behavior for v2 clients?  I'm trying to determine if I have a bug in my code.

**Comment by tammersaleh** [comment]
(also, thank you for your help on pebble - it's exactly what we needed for local testing!)

**Comment by tammersaleh** [comment]
Sorry, I just saw that [`acme` now supports this correctly](https://github.com/certbot/certbot/pull/7176).

**Comment by jsha** [comment]
Yep, you spotted it! The latest version of `acme` does the right thing.
