### ISSUE TITLE
Should Pebble pretend to be slow at certificate signing?

### ISSUE THREAD

**Issue by alexzorin** [letsencrypt/pebble#278]
I noticed that an ACME client has been getting away with assuming that the certificate will be available for download by the time that the finalize call returns.

That seems to basically be a result of Boulder's implementation. From my reading, it's impossible for the caller of finalize to observe a `processing` state. (That said, any other requests that occur while finalize is in-flight, could hypothetically observe it).

To mitigate this, I propose a mandatory random sleep before the order's `CertificateObject` is persisted.

I wanted to ask before writing a PR though, because it seems like there's a couple of different cases:

- Assuming that the certificate will be available upon the finalize response (Pebble already seems to mitigate this, so *I think* the change would not be necessary).
- Assuming the certificate will be available "soon" after the finalize response (e.g. on the following GET to the order). That's the one I'm thinking of, but I'm not sure whether it's worthwhile or not.

**Comment by cpu** [comment]
@alexzorin Adding a sleep to expose the order processing state to clients for a variable amount of time sounds good to me. It's definitely a place I expect clients have over-fit Boulder's behaviour. I suspect there's at least one or two clients that would out-right fail to handle an order in "processing", treating it as an unknown state.

**Comment by shred** [comment]
Please remember to add an option to change the sleep time, or turn it off (maybe similar to `PEBBLE_VA_SLEEPTIME` and `PEBBLE_VA_NOSLEEP`). For simple integration tests, random sleeps just consume time, without having an effect on the test result.

**Comment by cpu** [comment]
Agreed! Variable should include 0 length :-)
