### ISSUE TITLE
is alpn suppose to set supported protocols in client hello?

### ISSUE THREAD

**Issue by james-lawrence** [letsencrypt/pebble#296]
sorry if this is the wrong place:

I was looking at how [caddy implemented ALPN](https://github.com/caddyserver/caddy/pull/2201). and noticed they used the supported protocols to detect the negotiation. however when attempting to test using pebble, no such protocols were listed in the hello.

**Comment by cpu** [comment]
Hi @james-lawrence, thanks for the question.

I can't speak to Caddy's implementation but I can confirm that Pebble is sending the correct ALPN extension in the TLS Client Hello per https://tools.ietf.org/html/draft-ietf-acme-tls-alpn-07#section-3

Here's a snippet of the decoded TLS Client Hello captured running a packet capture on the Pebble host while a TLS-ALPN-01 challenge for `test.com` is initiated using `tshark -i any -f 'tcp port 5001' -n -V -Y 'ssl.handshake.type == 1'`:

```
Secure Sockets Layer
    TLSv1 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 224
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 220
            Version: TLS 1.2 (0x0303)
            Random: dcf21c80ccc6c6a9871e8332686b9f8177d8161ec78e2c05...
                GMT Unix Time: Jun 19, 2087 05:48:48.000000000 EDT
                Random Bytes: ccc6c6a9871e8332686b9f8177d8161ec78e2c054f4b0c9f...
            Session ID Length: 32
            Session ID: fb74c333fe8035975eb8d8ce476b3efef9c2f3f4d11416bc...
            Cipher Suites Length: 32
            Cipher Suites (16 suites)
<snipped>
            Compression Methods Length: 1
            Compression Methods (1 method)
                Compression Method: null (0)
            Extensions Length: 115
            Extension: next_protocol_negotiation (len=0)
                Type: next_protocol_negotiation (13172)
                Length: 0
            Extension: server_name (len=13)
                Type: server_name (0)
                Length: 13
                Server Name Indication extension
                    Server Name list length: 11
                    Server Name Type: host_name (0)
                    Server Name length: 8
                    Server Name: test.com
<snipped>
            Extension: application_layer_protocol_negotiation (len=13)
                Type: application_layer_protocol_negotiation (16)
                Length: 13
                ALPN Extension Length: 11
                ALPN Protocol
                    ALPN string length: 10
                    ALPN Next Protocol: acme-tls/1
            Extension: signed_certificate_timestamp (len=0)
                Type: signed_certificate_timestamp (18)
                Length: 0
<snipped>
```

I'm not aware of any divergences between Pebble's TLS-ALPN-01 implementation and Boulder's production implementation. Both set the required `"acme-tls/1"` ALPN extension the same way with the `NextProtos` field of a `tls.Config` structure:

https://github.com/letsencrypt/pebble/blob/295d9c1182f27616cd91770f5e535e85a37e2cb9/va/va.go#L374

**Comment by james-lawrence** [comment]
kk i'll dig further

**Comment by cpu** [comment]
Sounds good :+1:

>  however when attempting to test using pebble, no such protocols were listed in the hello.

If you add some more information about how you tested Caddy with Pebble to this issue maybe @mholt would have an idea about what the hangup could be.

**Comment by james-lawrence** [comment]
wasnt testing caddy, I was using their implementation as a reference. I suspect human error on my part atm.

**Comment by cpu** [comment]
> wasnt testing caddy, I was using their implementation as a reference.

Ahhh! Apologies for misunderstanding. :+1: 

(_if you see this, sorry about the unnecessary mention Matt! :-)_)

**Comment by james-lawrence** [comment]
yup human error. had to set the NextProtos field in the tls.Config.

**Comment by cpu** [comment]
Thanks for following up @james-lawrence, glad you were able to figure things out.
