### ISSUE TITLE
Allow CA cert/key configuration

### ISSUE THREAD

**Issue by 256dpi** [letsencrypt/pebble#298]
In my setup I'm using https://github.com/FiloSottile/mkcert to generate a CA cert/key on my machine to generate "green" certificates for local development. As these CA cert/key are unique there is no harm from adding them to the system trust store and once in a while rotate them. Now, it would be awesome if the same CA cert/key could be used by pebble to issue certificates and by that automatically generate "green" certificates.

I'm happy to prepare a PR if I get a go in this.

**Comment by cpu** [comment]
:wave: Hi @256dpi, thanks for filing an issue.

I think https://github.com/FiloSottile/mkcert/issues/154 would be a better resolution for your use case. Perhaps the maintainers of mkcert would be open to you submitting a PR for that issue?

Pebble is designed primarily to be exercised to test ACME clients and isn't a great fit for producing certificates that should be consumed by developers for use with their applications. I'm hesitant to add configuration that makes it less ephemeral and more tempting to deploy in broader contexts.

**Comment by 256dpi** [comment]
Yes, generally that would be an options as well. However, in my setup I'm actually testing a service that interacts with Let's Encrypt as part of an E2E test. The said configuration would me allow to run the full E2E test without `Insecure` options on all the http clients that consume the resources secured with the issued certificate. Having this option would make the E2E tests stronger. What do you think?

**Comment by cpu** [comment]
>  However, in my setup I'm actually testing a service that interacts with Let's Encrypt as part of an E2E test. The said configuration would me allow to run the full E2E test without Insecure options on all the http clients that consume the resources secured with the issued certificate

Thanks for the added context. It definitely makes your feature request understandable.

Instead of using a fixed Pebble root CA could your E2E test automation configure the trust store of the relying party clients with the generated CA certificate using the [Pebble management interface's `/roots` endpoint](https://github.com/letsencrypt/pebble#ca-root-and-intermediate-certificates)?

**Comment by 256dpi** [comment]
Thanks for the hint. That would be indeed an option just for the automated E2E test. But since I'm regularly running the test son my laptop und use my browser to check what's wrong, a trusted root would still be favorable. I hoped to find and easy solution for both things. 😄

**Comment by cpu** [comment]
> Thanks for the hint. That would be indeed an option just for the automated E2E test. 

Great, :+1: Let us know if you hit any problems with this approach.

> since I'm regularly running the test son my laptop und use my browser to check what's wrong, a trusted root would still be favorable.

Adding the Pebble CA to an end user browser trust store is exactly what I'm hoping to discourage :laughing: That's a practice that makes me pretty nervous.

@jsha What do you think? Am I being too conservative?

**Comment by jsha** [comment]
I agree. We set some fairly conservative goals when we began Pebble in order to keep its scope narrow, and one of the most important ones was that it should not be used as a regular CA where you might install the trust root, because we intentionally have all sorts of non-secure test hooks in Pebble that would make it unsuitable as such a CA.

We chose to make Pebble generate a fresh root on every startup specifically to discourage the types of uses that we think are unsafe and that we don't want to support. I still think that's a good decision, so I think we should not allow configuration of a specific CA key.

Sorry that this doesn't solve your use case, @256dpi. I hope you find another way through!

**Comment by mmalone** [comment]
A bit of shameless self-promotion here, but if anyone comes across this issue and is looking for an internal CA that speaks ACME and _is_ designed for production use cases check out [`step-ca`](https://github.com/smallstep/certificates). We wrote [a blog post with lots more info on our ACME support](https://smallstep.com/blog/private-acme-server/).

It's not as simple as `mkcert`, but our [`step` tool](https://github.com/smallstep/cli) integrates with `step-ca` to automate certificate management. The `step certificate install` subcommand can be used to do what `mkcert` does. For more details see [this blog post](https://smallstep.com/blog/step-v0-8-6-valid-https-certificates-for-dev-pre-prod/).

In my opinion, if you're _just_ looking for a simple tool to create certs that work for local development, use `mkcert`. If you're testing an ACME integration, use `pebble` (_and_ `step-ca`, as a second data point :). If you need something more sophisticated, like an ACME CA that you can bring into staging or run in production for server-to-server mTLS, check out `step` & `step-ca`!

**Comment by 256dpi** [comment]
@mmalone I switched to it already! 😄 The only thing missing was https://github.com/smallstep/certificates/pull/172, but it was easy to implement.

**Comment by cpu** [comment]
@mmalone Thanks for posting :-)

> In my opinion, if you're just looking for a simple tool to create certs that work for local development, use mkcert. If you're testing an ACME integration, use pebble (and step-ca, as a second data point :). If you need something more sophisticated, like an ACME CA that you can bring into staging or run in production for server-to-server mTLS, check out step & step-ca!

This opinion matches up with my own. I think it would be nice to capture these options in the Pebble README.

@mmalone Would you be up for writing a small Pebble README PR or should I take a crack at that?
