### ISSUE TITLE
Documentation: add Node Pebble installation instructions to Install section

### ISSUE THREAD

**Issue by aral** [letsencrypt/pebble#310]
I just created a Node module called Node Pebble that makes it trivial to launch and use Pebble in unit tests from Node.js:

https://www.npmjs.com/package/@small-tech/node-pebble

It could help client developers working with Node.js if is mentioned in the Install and Usage sections. e.g., 

```md
## Install

### Binary
… (see #308)
### Go
…
### Node.js
`​``sh
npm install @small-tech/node-pebble
`​``

## Usage
…
### Node.js
`​``js
const Pebble = require('node-pebble')

(async () => {
  await Pebble.ready()
  // Run your tests…
  await Pebble.shutdown()
}()
`​``
```

Note that as of the latest version of Node Pebble, the module automatically handles patching Node.js’s TLS module to accept the Pebble test cert as well as the dynamically-generated Pebble root and intermediary CA certificates so when `await Pebble.ready()` returns, Node.js is ready accept responses from Pebble without any further work on the part of the developer.

Happy to prepare a pull request for this if you feel it’s worthwhile to include it.

Related #308, #309

**Comment by jsha** [comment]
Thanks so much for letting us know! Since this is specific to one language environment I don't think it makes sense to add to our overall README, but hopefully other folks who are doing Node integrations will find this issue and through it, your module.

**Comment by aral** [comment]
Sure, closing :)
