### ISSUE TITLE
Add alternate chains of varying path length

### ISSUE THREAD

**Issue by alexzorin** [letsencrypt/pebble#318]
@jvanasco suggests in [this forum post](https://community.letsencrypt.org/t/workflow-for-using-alternate-link-relation/129321/7?u=_az) that ACME clients might not be able to handle downloading a certificate chain that is longer than just end-entity+issuer.

We could add this variation to strict mode.

These chains do happen in real life (check what certificates are sent by `gogetssl.com` for example) and since pretty much the entire point of Pebble is to be a stickler for the rules, I think it should be added.

**Comment by felixfontein** [comment]
I don't think this should be limited to strict mode, but it should be available always. For backwards compatibility, it should require explicit enabling though.

**Comment by jvanasco** [comment]
No client I've seen has handled this properly, until Certbot recently merged this PR (from @alexzorin of all people!) https://github.com/certbot/certbot/pull/7877/files  

For lack of time to properly handle this on my client, I just "do whatever certbot does".

The best-case typical client will correctly pull out the first cert... but then group all subsequent certs together into a "fullchain".  this is somewhat correct - most systems should handle this fine - however it does not differentiate between the discrete certs in the fullchain component.  (i.e. they always generates a 2 item chain; if there is one upchain cert then we see [cert, upchain] but if there are 2 or more upchain certs, we see [cert, upchain1+upchain2].

However... many clients just use regex or string splits, and pull out the 1st and 2nd items from the result.

**Comment by alexzorin** [comment]
Feedback welcome in #320!

**Comment by felixfontein** [comment]
@jvanasco I really wonder why no other client bothered to implement that, since it was pretty obvious from the RFC that this could happen. (I did implement it for my client, and the PR finally showed that the code I wrote actually works in real life ;) )
