### ISSUE TITLE
Authorization reuse and nonce rejection use deterministic "rand"

### ISSUE THREAD

**Issue by jerith** [letsencrypt/pebble#321]
According to the README, "Pebble will reuse valid authorizations in new orders, if they exist, 50% of the time" and `PEBBLE_AUTHZREUSE` can be set to change the probability. The relevant code agrees with this: https://github.com/letsencrypt/pebble/blob/4670b15b155dbd5138d5cbecf4966e497e9d48ac/wfe/wfe.go#L1489 The same applies to nonce rejection.

However, it seems that nothing in Pebble ever calls `rand.Seed()` and thus the PRNG emits the same sequence of values every run. (See https://golang.org/pkg/math/rand/#Seed for the documented behaviour.)

This can be a problem for automated test suites (like mine) that always make the same sequence(s) of calls to Pebble with very few opportunities for authorization reuse because multiple test runs (with a freshly-started Pebble for each) don't increase the chances of uncovering authorization reuse or nonce rejection bugs.

Given that Pebble is explicitly a testing server and generates new CA credentials every run, I think it would make sense to seed `rand` at startup so that every test run provides new opportunities to uncover bugs.

**Comment by aarongable** [comment]
Thanks for reporting this! Obviously a good idea, so, done!
