### ISSUE TITLE
CSR contains a public key for a known account

### ISSUE THREAD

**Issue by cheungtitus** [letsencrypt/pebble#326]
Am using Ansible to obtain a certificate from Pebble using DNS challenge.  The challenge TXT record was obtained from Pebble and updated on the DNS server successfully but am given the following error when using the [acme_certificate](https://docs.ansible.com/ansible/latest/collections/community/crypto/acme_certificate_module.html) module to have Pebble to do the validation against the inserted TXT record.
`fatal: [dnsmaster]: FAILED! => {"changed": false, "msg": "Error new cert: CODE: 400 RESULT: {'type': 'urn:ietf:params:acme:error:badCSR', 'detail': 'CSR contains a public key for a known account', 'status': 400}", "other": {}}`

Has anyone seen this?  Not sure why it's saying the CSR has a public key for a known account.  I have generated the CSR using the [openssl_csr](https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_csr_module.html) module.

**Comment by felixfontein** [comment]
This happens if you use the same private key as the account key **and** the certificate's private key. You must use different private keys for these two things.

**Comment by cheungtitus** [comment]
@felixfontein perfect thanks.  That was exactly the problem.  Would have taken me ages to spot this.  In case someone else come across this as well.  A private key is used to generate the CSR and another private key is used to get the [challenge] and do the [challenge validation and certificate retrieval].

**Comment by jsha** [comment]
Thanks for posting the answer, @felixfontein !
