### ISSUE TITLE
trouble with replay-nonce

### ISSUE THREAD

**Issue by icing** [letsencrypt/pebble#335]
Finally getting around to configuring the mod_md test suite against pebble. My setup:

```
> pebble -config test/config/pebble-config.json -dnsserver _8053
> # apache is to answer on the challenge ports
> pebble-challtestsrv -http01 '' -https01 '' -tlsalpn01 ''
```

Quite reliably, the communication with pebble fails with a ``` urn:ietf:params:acme:error:badNonce: JWS has an invalid anti-replay nonce:```. If I increase my client logging, the likelihood decreases(!).

mod_md uses libcurl which negotiates HTTP/2 with pebble (nice!). However, as it is now, libcurl uses a new connection for each request.

I attach a verbose log of the client, failred request at the end. To me, this is reads as mod_md using the last returned nonce correctly. It could be a bug in my client, but it works so reliably with boulder, maybe there is a situation where pebble's nonce updates across connections is not fast enough?

[mod_md_test_502_100-FAILED.log](https://github.com/letsencrypt/pebble/files/5731131/mod_md_test_502_100-FAILED.log)

Thanks for any help in resolving this.
Stefan

PS. @cpu asked for this - don't look at me...

**Comment by cpu** [comment]
> PS. @cpu asked for this - don't look at me...

:laughing: 

> Quite reliably, the communication with pebble fails with a urn:ietf:params:acme:error:badNonce: JWS has an invalid anti-replay nonce

@icing To rule out the most likely things first have you tried setting the `PEBBLE_WFE_NONCEREJECT` environment variable to `PEBBLE_WFE_NONCEREJECT=0` for your `pebble` instance? Pebble [by design](https://github.com/letsencrypt/pebble#invalid-anti-replay-nonce-errors) defaults to throwing this error some percentage of the time in order to test that clients follow the spec and retry bad nonce errors.

**Comment by icing** [comment]
Tricksy hobbits! Yes, if I tell pebble to not throw a tantrum, this test runs reliably. 

Hmm, I thought I had proper retries on bad nonces, but to verify that, I'd need a test server...wait!

Will update here on my progress. Thanks for the support!

**Comment by icing** [comment]
Ok, first successful run with pebble. Had to skip the stapling tests and some validation triggers as pebble certs are valid slightly longer than expected.

I see that the 'tls-apln-01' challenges take longer than they should. Need to look into that. Also the nonce handling needs to be fixes. Will probably look again in a few days.

**Comment by cpu** [comment]
> I see that the 'tls-apln-01' challenges take longer than they should.

Interesting! I would try adding [`PEBBLE_VA_NOSLEEP=1`](https://github.com/letsencrypt/pebble#testing-at-full-speed) to your env to see if that helps. It's possible the TLS-ALPN-01 challenges had unlucky RNG and slept for longer than the other challenges.

**Comment by icing** [comment]
Testing again today. The things pebble prints during an ```tls-alpn-01``` challenge. mod_md times out after having monitored the pending challenge for a while, and tries a second time. Then pebble reports "Pulling task from..." and sends a request to Apache.

I can see in the apache logs that pebble does not contact apache on the first attempt. Maybe there is something that is missing in the first challenge trigger? Can I get more detailed logging from pebbble?

```
Pebble 2020/12/28 12:27:59 ACME directory available at: https://0.0.0.0:14000/dir
Pebble 2020/12/28 12:28:06 GET /dir -> calling handler()
Pebble 2020/12/28 12:28:06 HEAD /nonce-plz -> calling handler()
Pebble 2020/12/28 12:28:06 POST /sign-me-up -> calling handler()
Pebble 2020/12/28 12:28:06 There are now 1 accounts in memory
Pebble 2020/12/28 12:28:06 POST /order-plz -> calling handler()
Pebble 2020/12/28 12:28:06 There are now 1 authorizations in the db
Pebble 2020/12/28 12:28:06 Added order "0Z_2MzW0lUoNmSihkAnex4UldLAYQ57KoM8ufFCiezs" to the db
Pebble 2020/12/28 12:28:06 There are now 1 orders in the db
Pebble 2020/12/28 12:28:06 POST /my-order/ -> calling handler()
Pebble 2020/12/28 12:28:06 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:07 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:07 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:07 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:07 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:08 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:10 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:13 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:19 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:29 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:37 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:41 GET /dir -> calling handler()
Pebble 2020/12/28 12:28:41 HEAD /nonce-plz -> calling handler()
Pebble 2020/12/28 12:28:41 POST /my-account/ -> calling handler()
Pebble 2020/12/28 12:28:41 POST /my-order/ -> calling handler()
Pebble 2020/12/28 12:28:41 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:41 POST /chalZ/ -> calling handler()
Pebble 2020/12/28 12:28:41 Pulled a task from the Tasks queue: &va.vaTask{Identifier:acme.Identifier{Type:"dns", Value:"test-702-004-1609154886.org"}, Challenge:(*core.Challenge)(0xc0005c4140), Account:(*core.Account)(0xc0000941e0)}
Pebble 2020/12/28 12:28:41 Starting 3 validations.
Pebble 2020/12/28 12:28:41 Sleeping for 1s seconds before validating
Pebble 2020/12/28 12:28:41 Sleeping for 0s seconds before validating
Pebble 2020/12/28 12:28:41 Sleeping for 3s seconds before validating
Pebble 2020/12/28 12:28:41 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:41 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:41 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:41 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:42 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:44 authz lhhOVgnUbzbHgEUrN7Ko1DMBCgaT6e8TxvKaJPWU4Kw set VALID by completed challenge jlutKJS4Z_9byBAnJbO4uuywGHlTE-fErazfDzQOZJM
Pebble 2020/12/28 12:28:44 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:28:44 POST /my-order/ -> calling handler()
Pebble 2020/12/28 12:28:44 POST /finalize-order/ -> calling handler()
Pebble 2020/12/28 12:28:44 Order 0Z_2MzW0lUoNmSihkAnex4UldLAYQ57KoM8ufFCiezs is fully authorized. Processing finalization
Pebble 2020/12/28 12:28:44 Issued certificate serial 23b83d38b6bd0b12 for order 0Z_2MzW0lUoNmSihkAnex4UldLAYQ57KoM8ufFCiezs
Pebble 2020/12/28 12:28:44 POST /my-order/ -> calling handler()
Pebble 2020/12/28 12:28:44 POST /certZ/ -> calling handler()
```

Compared to a ```http-01``` challenge which reliably works on first attempt:

```
Pebble 2020/12/28 12:30:33 GET /dir -> calling handler()
Pebble 2020/12/28 12:30:33 HEAD /nonce-plz -> calling handler()
Pebble 2020/12/28 12:30:33 POST /sign-me-up -> calling handler()
Pebble 2020/12/28 12:30:33 There are now 1 accounts in memory
Pebble 2020/12/28 12:30:33 POST /order-plz -> calling handler()
Pebble 2020/12/28 12:30:33 There are now 1 authorizations in the db
Pebble 2020/12/28 12:30:33 Added order "o7r1MbXoG41f2TCjSQw4nM6pjD0UDxjjbEfxAsCV3RI" to the db
Pebble 2020/12/28 12:30:33 There are now 1 orders in the db
Pebble 2020/12/28 12:30:33 POST /my-order/ -> calling handler()
Pebble 2020/12/28 12:30:33 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:30:33 POST /chalZ/ -> calling handler()
Pebble 2020/12/28 12:30:33 Pulled a task from the Tasks queue: &va.vaTask{Identifier:acme.Identifier{Type:"dns", Value:"test-702-004-1609155033.org"}, Challenge:(*core.Challenge)(0xc000574640), Account:(*core.Account)(0xc0005c6c60)}
Pebble 2020/12/28 12:30:33 Starting 3 validations.
Pebble 2020/12/28 12:30:33 Sleeping for 1s seconds before validating
Pebble 2020/12/28 12:30:33 Sleeping for 1s seconds before validating
Pebble 2020/12/28 12:30:33 Sleeping for 2s seconds before validating
Pebble 2020/12/28 12:30:33 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:30:34 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:30:34 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:30:34 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:30:34 Attempting to validate w/ HTTP: http://test-702-004-1609155033.org:5002/.well-known/acme-challenge/Df1n49v-MPHKy31TZ0_RjO9GCbS2Af4x6RcKaacQut8
Pebble 2020/12/28 12:30:34 Attempting to validate w/ HTTP: http://test-702-004-1609155033.org:5002/.well-known/acme-challenge/Df1n49v-MPHKy31TZ0_RjO9GCbS2Af4x6RcKaacQut8
Pebble 2020/12/28 12:30:35 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:30:35 Attempting to validate w/ HTTP: http://test-702-004-1609155033.org:5002/.well-known/acme-challenge/Df1n49v-MPHKy31TZ0_RjO9GCbS2Af4x6RcKaacQut8
Pebble 2020/12/28 12:30:35 authz PnOCbqwUlMuOAhJFZPXf6mYiJ6kZ1nK59Lhot_PwN_E set VALID by completed challenge US7En1Di9b4ZfphqhowNaTvalBgJsTh3gmePaGpJDZI
Pebble 2020/12/28 12:30:37 POST /authZ/ -> calling handler()
Pebble 2020/12/28 12:30:37 POST /my-order/ -> calling handler()
Pebble 2020/12/28 12:30:37 POST /finalize-order/ -> calling handler()
Pebble 2020/12/28 12:30:37 Order o7r1MbXoG41f2TCjSQw4nM6pjD0UDxjjbEfxAsCV3RI is fully authorized. Processing finalization
Pebble 2020/12/28 12:30:37 Issued certificate serial 31ce909c8866afea for order o7r1MbXoG41f2TCjSQw4nM6pjD0UDxjjbEfxAsCV3RI
Pebble 2020/12/28 12:30:37 POST /my-order/ -> calling handler()
Pebble 2020/12/28 12:30:37 POST /certZ/ -> calling handler()
```

**Comment by icing** [comment]
Hmm, looking at it again, I notice that:

```
POST /chalZ/ -> calling handler()
```

is missing on the first tls-alpn-01 attempt. Will debug.

**Comment by icing** [comment]
Ok, found and fixes it in master. Was a bug in the new code for multiple certificates (ECDSA+RSA) for a domain.

Now I need only to fix the behaviour for nonces in denial and then we are clean.

**Comment by icing** [comment]
more of the bugs in mod_md have been fixed and the test suite runs now also with pebble's nonce dementia. That was indeed helpful in catching cases. Thanks for that!

**Comment by jsha** [comment]
Yay, I'm very glad that feature helped catch bugs! And thanks for sharing your process here. Hopefully it helps future adventurers.
