### ISSUE TITLE
Override the certificate validity period

### ISSUE THREAD

**Issue by TheJoelGray** [letsencrypt/pebble#368]
I see the PR for #361 and have downloaded and built my own image. I tried to figure out how to configure this to a value other than the default but I must be missing something. I tried setting `"certValidityPeriod": 1728000` in the pebble-config.json that I'm using in my container but my certificates still come out with a 5 year validity period.

I have verified that the config file in my container has that value in it and looking at the logs it's not being used.

`Pebble 2021/11/15 17:32:41 Using certificate validity period of 157766400 seconds`

I'm just trying to do this to test out a renewal system so it would b super helpful.

Thanks! 
-Joel

**Comment by aarongable** [comment]
The name of the config key is `certificateValidityPeriod`, not `certValidityPeriod`. Does that resolve your issue?

**Comment by TheJoelGray** [comment]
Oh wow...must have been too late and I missed that I had it wrong. That did resolve it, thank you!!!

-Joel
