### ISSUE TITLE
Unable to verify cert chain with openssl

### ISSUE THREAD

**Issue by camertron** [letsencrypt/pebble#375]
Hey pebble peeps! First of all, thanks for pebble. With the exception of the issue I'm about to describe, it's been working really well for the e2e tests I'm working on.

For some reason (probably a lack of understanding on my part), I am unable to verify my server's cert using openssl. I have pebble, challtestsrv, and cert-manager running inside a local Kind cluster. I also have an `Issuer` object pointed at pebble, and an `Ingress` object using the `Issuer`. The whole ACME HTTP-01 dance works as expected, a `Certificate` object is created, and the cert data gets stored in a k8s `Secret`.

I then grab both the root and intermediate certs using the pebble management interface and store them on disk, as well as the end entity cert from the k8s `Secret`. OpenSSL is able to verify the self-signed root cert:

```bash
openssl verify -CAfile pebble.root.crt pebble.root.crt
pebble.root.crt: OK
```

And the intermediate cert looks ok too:

```bash
openssl verify -CAfile pebble.root.crt pebble.intermediate.crt
pebble.intermediate.crt: OK
```

But when I try to verify the end entity cert that was stored in the k8s `Secret`, this happens:

```bash
openssl verify -CAfile pebble.root.crt -untrusted pebble.intermediate.crt pebble.server.crt
pebble.server.crt: serialNumber = 1234567890
error 20 at 0 depth lookup:unable to get local issuer certificate
```

I've tried everything I can think of, including combining the root and intermediate certs into a single file. I'm forced to conclude that pebble.server.crt wasn't signed by pebble.intermediate.crt, which doesn't make any sense to me. Isn't that the whole point of pebble?

Any help you could provide would be most appreciated!

**Comment by jsha** [comment]
`openssl verify` is remarkably unintuitive in its arguments. I can never remember what the exact right set of arguments is (there's a thread on the forum where I and a forum member eventually figured it out), but the short story is it's almost always the wrong tool for the job. It's much better to do something like `openssl s_client -connect example.com:443` (which understands the specific logic to verify TLS server auth certificates).

If you can tell us more about the specific problem you're trying to solve, we might be able to suggest an alternate solution that works better than `openssl verify`.

**Comment by camertron** [comment]
Hey @jsha, thanks for responding! I'm actually trying to make a cURL request to the app running behind the aforementioned ingress object. I'm passing the `--cacert` flag and have tried both the root and intermediate certs, but I get the same error openssl was giving me (I have edited my /etc/hosts file to resolve kubytest.io as 127.0.0.1):

```
$> curl -vvv --cacert pebble.root.crt https://kubytest.io
*   Trying 127.0.0.1:443...
* Connected to kubytest.io (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: pebble.chain.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Interestingly, if I use localhost instead and pass the `Host` header, this happens:

```
$> curl -vvv --cacert pebble.root.crt -H "Host: kubytest.io" https://localhost
*   Trying 127.0.0.1:443...
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: pebble.root.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Which I suppose makes sense? I read somewhere you're not allowed to have a self-signed cert in the chain, but I thought that's what the `--cacert` argument was for?

**Comment by jsha** [comment]
Here's what I would do to debug: run `openssl s_client -showcerts -connect localhost:443` and `openssl s_client -showcerts -connect kubytest.io:443`.

Each of those should show a list of certs in PEM form (`------ BEGIN CERTIFICATE -------`). For each of those certificates, run them through `openssl x509 -text -noout` (paste the certificate to stdin). That'll give you an idea of what the certificate chain is and how it differs in each case.

**Comment by camertron** [comment]
Not surprisingly `openssl s_client -showcerts -connect localhost:443` shows me a single cert with a common name of "Kubernetes Ingress Controller Fake Certificate".

However, `openssl s_client -showcerts -servername kubytest.io -connect kubytest.io:443` spits this out:

```
CONNECTED(00000003)
depth=0 serialNumber = 1234567890
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 serialNumber = 1234567890
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/serialNumber=1234567890
   i:/CN=cert-manager.local
-----BEGIN CERTIFICATE-----
MIICmjCCAfugAwIBAgIRAKdtsx0zki/paTAwfltDZHswCgYIKoZIzj0EAwQwHTEb
MBkGA1UEAxMSY2VydC1tYW5hZ2VyLmxvY2FsMB4XDTIyMDQwNzE3Mzg1N1oXDTIy
MDcwNjE3Mzg1N1owFTETMBEGA1UEBRMKMTIzNDU2Nzg5MDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAMwGA/DWtrq3bJRYk+yic/NWQo3a9uA/Rlx362Vq
mtaBBuCYfZHusfFKT3Hu+48/L9CaDjbV9YjHxqpLkNw3o1wu0q8GHLkw+HuEqYFQ
RFsIIDRsGR/18hBkDwcKR2iTLA0tzqETfsT/QdloQGGR7g+R28Pgtpj8gwYHSRq+
90zeUUq67pIAZWUSBB1Lshmt0AIbp9BkD7SoYT8JC+DP7b52YbZwGtE1NLdkEIF2
Yb9CCK1bUfeE3YYaqtGkXSWE4AIus1C3aXjxsw2uVs7DuBZh/KSQb+WN5h06RTqS
we4nBAnoL61ebjzu5oqqIcv0RU9Og7oBT7aXwi22B9xYXxsCAwEAAaNZMFcwDgYD
VR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUjssl2pIaHiJg
FpdR+rgVDQcNs0QwFgYDVR0RBA8wDYILa3VieXRlc3QuaW8wCgYIKoZIzj0EAwQD
gYwAMIGIAkIB+4eqUE3lhrKs9XhtaBsLetBZWOCrTi7oBTHr4O8gWIFpDjTmKHVD
v+mq48wrScjndGsL7jLTAunq9SckwqheSTcCQgFJOa00GJa9m3q4FYT7BXR7EePu
VSy7JjQWpnHoerSBmEs6PUNfgqcq7d+vRB+nadL3VOe8wkgTpBqTLgi3wCgjLQ==
-----END CERTIFICATE-----
---
Server certificate
subject=/serialNumber=1234567890
issuer=/CN=cert-manager.local
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 1148 bytes and written 309 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 1889EA37C02CCBF22448561FE49DDF49D45D90DBDE66980E82A07BEB2BFDE805
    Session-ID-ctx: 
    Master-Key: 5DF71E7DBC6697E062BDB73B2FB6DD2DDE4C475C46046376A63692A9E44657F650859E2C7560E102F17841652E0F9E70
    Start Time: 1649449613
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
DONE
```

It doesn't seem to be able to fetch the entire chain? The cert it _does_ print out is the same one in the `Secret`. Running it through `openssl x509` gives this output:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            a7:6d:b3:1d:33:92:2f:e9:69:30:30:7e:5b:43:64:7b
    Signature Algorithm: ecdsa-with-SHA512
        Issuer: CN=cert-manager.local
        Validity
            Not Before: Apr  7 17:38:57 2022 GMT
            Not After : Jul  6 17:38:57 2022 GMT
        Subject: serialNumber=1234567890
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:cc:06:03:f0:d6:b6:ba:b7:6c:94:58:93:ec:a2:
                    73:f3:56:42:8d:da:f6:e0:3f:46:5c:77:eb:65:6a:
                    9a:d6:81:06:e0:98:7d:91:ee:b1:f1:4a:4f:71:ee:
                    fb:8f:3f:2f:d0:9a:0e:36:d5:f5:88:c7:c6:aa:4b:
                    90:dc:37:a3:5c:2e:d2:af:06:1c:b9:30:f8:7b:84:
                    a9:81:50:44:5b:08:20:34:6c:19:1f:f5:f2:10:64:
                    0f:07:0a:47:68:93:2c:0d:2d:ce:a1:13:7e:c4:ff:
                    41:d9:68:40:61:91:ee:0f:91:db:c3:e0:b6:98:fc:
                    83:06:07:49:1a:be:f7:4c:de:51:4a:ba:ee:92:00:
                    65:65:12:04:1d:4b:b2:19:ad:d0:02:1b:a7:d0:64:
                    0f:b4:a8:61:3f:09:0b:e0:cf:ed:be:76:61:b6:70:
                    1a:d1:35:34:b7:64:10:81:76:61:bf:42:08:ad:5b:
                    51:f7:84:dd:86:1a:aa:d1:a4:5d:25:84:e0:02:2e:
                    b3:50:b7:69:78:f1:b3:0d:ae:56:ce:c3:b8:16:61:
                    fc:a4:90:6f:e5:8d:e6:1d:3a:45:3a:92:c1:ee:27:
                    04:09:e8:2f:ad:5e:6e:3c:ee:e6:8a:aa:21:cb:f4:
                    45:4f:4e:83:ba:01:4f:b6:97:c2:2d:b6:07:dc:58:
                    5f:1b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier: 
                keyid:8E:CB:25:DA:92:1A:1E:22:60:16:97:51:FA:B8:15:0D:07:0D:B3:44

            X509v3 Subject Alternative Name: 
                DNS:kubytest.io
    Signature Algorithm: ecdsa-with-SHA512
         30:81:88:02:42:01:fb:87:aa:50:4d:e5:86:b2:ac:f5:78:6d:
         68:1b:0b:7a:d0:59:58:e0:ab:4e:2e:e8:05:31:eb:e0:ef:20:
         58:81:69:0e:34:e6:28:75:43:bf:e9:aa:e3:cc:2b:49:c8:e7:
         74:6b:0b:ee:32:d3:02:e9:ea:f5:27:24:c2:a8:5e:49:37:02:
         42:01:49:39:ad:34:18:96:bd:9b:7a:b8:15:84:fb:05:74:7b:
         11:e3:ee:55:2c:bb:26:34:16:a6:71:e8:7a:b4:81:98:4b:3a:
         3d:43:5f:82:a7:2a:ed:df:af:44:1f:a7:69:d2:f7:54:e7:bc:
         c2:48:13:a4:1a:93:2e:08:b7:c0:28:23:2d
```

Notice that the common name is certmanager.local, but the SAN is kubytest.io.

**Comment by jsha** [comment]
Looks like the certificate you're currently serving was generated by cert-manager, not by Pebble. Perhaps cert-manager installs a default certificate until it can successfully issue a "real" certificate from whatever ACME server you've configured, and it's having trouble reaching your Pebble instance?

(BTW I have to confirm at this point that you're using Pebble in testing infrastructure, not as a production CA :-D)

**Comment by camertron** [comment]
> Looks like the certificate you're currently serving was generated by cert-manager, not by Pebble.

^ This sent me down the right path. You were totally correct - I couldn't validate the cert because it wasn't issued by pebble! Thanks to that realization I have finally gotten things working. Let me explain for anyone who comes to this issue later:

### Solution Part I

Somewhere along the way I noticed that the additional ingress object cert-manager creates to respond to the ACME HTTP-01 challenge wasn't getting assigned an address. I was seeing weird dial errors in the cert-manager logs, so I thought maybe it was trying to hit the challenge URL too early and failing because no address had been assigned yet. Since the original ingress object had an address already, I thought I would try adding the `acme.cert-manager.io/http01-edit-in-place` annotation to make cert-manager edit the existing ingress instead of creating a new one. Unfortunately a side-effect of doing so also makes cert-manager install a fake cert on your ingress before the real one gets issued, I assume to ensure your ingress always speaks TLS? Not sure. (Side note: like, why even do this? Nobody will be able to make secure requests with a fake cert in place. Can you even get a copy of cert-manager's CA cert?)

Confusingly, doing a `kubectl get` on the `Certificate` object will report the cert as "Ready" even though it's clearly not. The first time I thought it had worked, the corresponding `CertificateRequest` and `Order` objects had also been deleted. I thought that must mean no more work needed to be done and the process had finished successfully. Wrong again.

Furthermore the edit-in-place annotation required that all traffic to my domain (kubytest.io) be TLS traffic, including requests made to ACME challenge URLs. According to the logs, cert-manager tries to make requests to http:// URLs, which would then fail because the ingress was configured to speak only TLS.

Side note: it was really hard to debug what was going on here because cert-manager would delete the ACME ingress object so quickly I couldn't examine it easily or try to send it any requests (it was available for only about 10 seconds).

Anyway, I removed the edit-in-place annotation.

### Solution Part II

Originally I started up both an instance of pebble and an instance of challtestsrv, but in an effort to simplify and rule out parts of the system I ended up stopping the instance of challtestsrv and instead started passing the `PEBBLE_VA_ALWAYS_VALID=1` environment variable to pebble. According to the docs, doing so will treat all challenge POST requests as valid. This ended up working. The `CertificateRequest` and `Order` objects are now both marked as "valid".

Most important of all though, I can now verify the entire cert chain by running

```bash
$> openssl verify -CAfile pebble.root.crt -untrusted pebble.intermediate.crt pebble.server.crt
pebble.server.crt: OK
```

Removing any of those arguments results in an error, so I'm pretty sure it's doing the right thing? Oh and also `openssl s_client -showcerts` works too 😄 

I would love to get challtestsrv working too, but damn this whole process has taken so much time I'm ready to say what I've got now is good enough.

> (BTW I have to confirm at this point that you're using Pebble in testing infrastructure, not as a production CA :-D)

Hahaha not to worry, I'm only using pebble in CI for end-to-end testing purposes. You can see the results [here](https://github.com/getkuby/kuby-core/actions/runs/2139574990).

**Comment by jsha** [comment]
Congratulations! I'm so glad we were able to help you solve your problem.

**Comment by jvanasco** [comment]
> `openssl verify` is remarkably unintuitive in its arguments. I can never remember what the exact right set of arguments is ([there's a thread on the forum where I and a forum member eventually figured it out](https://community.letsencrypt.org/t/choice-of-default-long-chain-vs-short-chain/161184/43?u=jsha))

I just came across this looking for an unrelated issue, and wanted to note a few things here:

1. You should be invoking it as `openssl verify -purpose sslserver`.  (I missed this FOR YEARS.)

2.  here are a few very similar commands that may work - but do slightly different things

Sometimes a partial chain is all you need , and I believe it ensures the order is right:

    openssl verify -purpose sslserver -partial_chain -trusted {Root.pem} {ChainInReverse.pem}

There are two ways to invoke the -CAfile option:

1. Newer versions accept multiple `-untrusted` args:

       openssl verify -purpose sslserver -CAfile {Root.pem} [[-untrusted {IntermediateN.pem}],] {Cert.pem}

2. Older versions only accept a single`-untrusted` arg, so you need to `cat` all the intermediates together:
   
       openssl verify -purpose sslserver -CAfile {Root.pem} -untrusted {Intermediates.pem} {Cert.pem}

I usually handle this in Python now. It's easier.
