### ISSUE TITLE
DNS-01 Challenge with a DoT only DNS server

### ISSUE THREAD

**Issue by mariuskimmina** [letsencrypt/pebble#390]
I am running a local DNS server, CoreDNS, which only responds to DNS over TLS queries. When I point pebble to this server with `--dnsserver 127.0.0.1:1053` the communicaton fails because pebble is trying to use UDP, which my CoreDNS server does not respond to. Is there a way to work around this? Can I somehow tell pebble to use DoT for it's DNS requests? I read through the configuration options but couldn't find anything related.

**Comment by jsha** [comment]
No, pebble does not support DoT.
