### ISSUE TITLE
Possible race condition in order finalization

### ISSUE THREAD

**Issue by iulianbarbu** [letsencrypt/pebble#402]
# Context

I am new to golang so please let me know if my understanding is correct. 

I've been struggling for some time to test a request certificate flow, using a Rust acme-client based on the `instant-acme` crate. The problem I was facing is that my client can not retrieve the certificate from the CA because the order finalization response doesn't contain a `certificate URL`.

I've looked through the pebble code base and saw these lines, which result in converting the core.order to a displayable Order, but this happens on my machine before the `CompleteOrder` coroutine ends, when it should populate the `existingOrder` with a certificateObject. I am running on an M1 pro macbook.

```go
        // This is done asynchronously from my understanding and we don't block waiting on it.
	go wfe.ca.CompleteOrder(existingOrder)

	// Set the existingOrder to processing before displaying to the user
	existingOrder.Status = acme.StatusProcessing

	addRetryAfterHeader(response, wfe.retryAfterOrder)

	// Prepare the order for display as JSON
        // This converts the core.Order to an acme.Order so to speak, but it should wait for the `CompleteOrder` so that it will be able to populate the certificate URL used by the acme client to download the certificate.
	orderReq := wfe.orderForDisplay(existingOrder, request)
```

# Naive solution
 
To make sure I am not hitting this case on my local setup I had to remove the `go` keyword from the `wfe.ca.ComleteOrder` call to make sure the changes on the `existingOrder` will take place before running into `orderToDisplay`. I think there should be some synchronisation between the `CompleteOrder` and `orderToDisplay` calls (given the second depends on the completion of the first - as in making sure we populate the `CertificateObject` on the `existingOrder` before the call for `orderToDisplay`). I would be happy to contribute with a solution to my issue.

Of course, I am open to understanding what a proper solution might look like - if anyone knows we should do more than simply avoid the goroutine for the `CompleteOrder` call.

**Comment by felixfontein** [comment]
When you call finalize, you tell the CA to start finalizing the order (basically that you are done with your part). Once you call finalize, the order will be in the processing state, and only once the state changes to valid the certificate will be available. So the behavior you describe is intentional and to be expected. You need to fix your client to wait for the order to finish (in valid or invalid state).
