### ISSUE TITLE
ACME Renewal Information (ARI)

### ISSUE THREAD

**Issue by mholt** [letsencrypt/pebble#403]
Hi -- does pebble support ARI yet? I did a search but couldn't find any commits or issues referring to it. I'm starting to implement it into acmez/CertMagic/Caddy, but if it's not in pebble yet I'm just wondering if I should test against LE staging for now?

Thanks!

**Comment by jvanasco** [comment]
Pebble still doesn't have ARI.

Certbot recently dropped Boulder in favor of Pebble as the testing mechanism - See https://github.com/certbot/certbot/pull/9918

Given that new utilization by the largest ACME client, I think we can consider the lack of ARI functionality by Pebble as a roadblock widespread adoption.

[I would code a PR, but my Go knowledge is limited and I don't have enough bandwidth to expand my capabilities here to make a quality PR]

**Comment by pgporada** [comment]
I've got a work in progress started [here](https://github.com/letsencrypt/pebble/pull/461).

**Comment by jvanasco** [comment]
@pgporada I <HEART> you. Thank you!  I'll be monitoring that PR so I can better understand how this works and (hopefully) provide quality PRs in the future.

**Comment by mholt** [comment]
This is great, thank you. As soon as that's ready I'll prioritize implementing ARI.

**Comment by pgporada** [comment]
@mholt @jvanasco ARI support has landed as of https://github.com/letsencrypt/pebble/pull/461.
