### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by wlmarion** [letsencrypt/pebble#405]
I deactivated an account with acme.sh and now I am unable to find a way to reactivate the account or delete it to re-register. Where is the account data at in Pebble so I can fully delete an account to re-register it? I have combed through all the files under my pebble directory with no luck.

**Comment by jsha** [comment]
Hi @wlmarion! Pebble is testing CA, not a production CA, so it keeps all its data in memory and forgets it every time it restarts. So you can just restart Pebble.

The ACME protocol doesn't provide a way to reactivate accounts. But also, you shouldn't have to delete an account to create a new one with a different key.

**Comment by wlmarion** [comment]
Wow, that was embarrassingly simple. Thank you @jsha! Now I can continue working on the other issues I am having haha.
