### ISSUE TITLE
Missing TZ data in Docker container

### ISSUE THREAD

**Issue by lirc571** [letsencrypt/pebble#411]
When running pebble in Docker using the Dockerfile at `docker/pebble/linux.Dockerfile`, sometimes the request for fetching authorization object produces the error `missing Location in call to Time.In` from the lines below:

https://github.com/letsencrypt/pebble/blob/b7dddc09eb7051c1ec3838f3771b1647df1288c8/wfe/wfe.go#L2513-L2514

It can be fixed by installing tzdata in the container:

```Dockerfile
RUN apk --no-cache add tzdata
```

Not sure why the error only occurs some of the times.

**Comment by emfax** [comment]
I'm seeing this too.

Adding `tzdata` in the running container also fixes the issue.

**Comment by mcpherrinm** [comment]
We eliminated the call to LoadLocation in #439, so I think this shouldn't be a problem anymore.
