### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by NoamGaloz** [letsencrypt/pebble#443]
please create a new release with the updated go version

**Comment by mcpherrinm** [comment]
We will make one soon, once the current round of CI and linting fixes land.

**Comment by NoamGaloz** [comment]
Can I expect it to happen in a few more days? Weeks?

**Comment by mcpherrinm** [comment]
Depends how long #444 takes. Probably a few days, maybe a week.

**Comment by mcpherrinm** [comment]
v2.5.0 has been tagged

**Comment by ldez** [comment]
@mcpherrinm It seems there is a right problem https://github.com/letsencrypt/pebble/actions/runs/8256681739/job/22585865735

**Comment by mcpherrinm** [comment]
Yeah, I see the docker push failed.  I'll look into it tomorrow and probably cut a v2.5.1 if needed. I fixed the release notes.

**Comment by ldez** [comment]
There is a typo inside the release description of v2.5.1

> Identical to v2.5.1

https://github.com/letsencrypt/pebble/releases/tag/v2.5.1

I think it's "Identical to v2.5.**0**" :smile:
