### ISSUE TITLE
v2.5.0 docker push failed

### ISSUE THREAD

**Issue by mcpherrinm** [letsencrypt/pebble#447]
Permissions issue?

**Comment by ldez** [comment]
There is a typo inside the release description of v2.5.1

> Identical to v2.5.1

https://github.com/letsencrypt/pebble/releases/tag/v2.5.1

I think it's "Identical to v2.5.**0**" :smile:

**Comment by mcpherrinm** [comment]
Hm, well, yes it is tautologically identical to itself!
We've mostly sorted out the permissions now.

**Comment by mcpherrinm** [comment]
done

**Comment by shred** [comment]
Maybe I misunderstood the goal of this issue, but at https://hub.docker.com/r/letsencrypt/pebble there is still no update.

**Comment by aarongable** [comment]
It's at https://github.com/letsencrypt/pebble/pkgs/container/pebble now.

**Comment by shred** [comment]
Thank you... The README.md still refers to docker.com, so I wasn't aware of the new location.

**Comment by mcpherrinm** [comment]
Thanks, I'll update the README.
