### ISSUE TITLE
New Certificates aren't getting Ready

### ISSUE THREAD

**Issue by NoamGaloz1** [letsencrypt/pebble#454]
After every restart of Pebble pod (from any reason) -
- New certificates aren't getting Ready, stuck with error : ''Failed to create Order: 400 urn:ietf:params:acme:error:malformed: Key ID(kid) in JWS header missing expected URL prefix''.
- Only after deletion and re-creation of Pebble's cluster issuer, new certificates are getting ready.

It's like something in the restarting of pebble's pod is breaking the synchronization between pebble cluster issuer and the cert-manager (https://github.com/cert-manager/cert-manager) which we are using to send the certificate requests to the Certificate Authorities.

**Comment by pgporada** [comment]
This sounds like you're running something highly custom - pebble in kubernetes. Can you post an example pebble cluster issuer resource?
