### ISSUE TITLE
[Feature] Pebble should return Content-Type headers with charset

### ISSUE THREAD

**Issue by shred** [letsencrypt/pebble#46]
The ACME specs' examples give Content-Type headers like `Content-Type: application/json`, and Pebble also responds with that header. However, `Content-Type: application/json; charset=utf-8` or `Content-Type: application/json; charset="utf-8"` would be perfectly valid response content types as well.

If a client is implemented to only expect "application/json" as content type, it would fail if a charset is given along with the type.

Maybe Pebble should add the charset parameter to its response. Or randomly respond either with or without charset.

**Comment by cpu** [comment]
> Maybe Pebble should add the charset parameter to its response. Or randomly respond either with or without charset.

I'm a +1 for this idea. It sounds useful!

If you feel up to submitting a PR that would be awesome. If not I'll take this when time permits, it probably won't be for the next week or so unfortunately.

**Comment by shred** [comment]
See PR #53. Maybe a random header would be a little too much, so I just added a `charset=utf-8` to all responses.

**Comment by cpu** [comment]
Thanks for the PR @shred!
