### ISSUE TITLE
Support profile selection

### ISSUE THREAD

**Issue by aarongable** [letsencrypt/pebble#471]
Add a new "profile" field to the order resource (both in newOrder requests and subsequent order responses). Add a new "profiles" field to the directory resource, listing and describing the available profiles. Add configuration support to the WFE and CA to configure profiles.

The implementation should outwardly match Boulder and the planned ACME Profiles draft RFC.

**Comment by felixfontein** [comment]
> The implementation should outwardly match Boulder and the planned ACME Profiles draft RFC.

Does that draft RFC already exist, resp. is there a link to it somewhere? I wasn't able to find anything so far (also not on https://datatracker.ietf.org/wg/acme/documents/).

**Comment by felixfontein** [comment]
Actually now I found https://mailarchive.ietf.org/arch/msg/acme/BLVAayrTrUCegT4s2twci3Q2BY8/. I guess it's related to this?

**Comment by aarongable** [comment]
Correct. This PR says "_planned_ ACME Profiles draft RFC" for a reason -- we [discussed it at IETF 120](https://datatracker.ietf.org/doc/minutes-120-acme-202407261630/#profiles-proposal-aaron-gable) but I haven't yet submitted the document.
