### ISSUE TITLE
Hardcoded scheme in expectedURL at wfe.verifyPost()

### ISSUE THREAD

**Issue by marsangr** [letsencrypt/pebble#54]
I just deployed Pebble behind an HTTPS termination, but communication attempts were rejected because of these lines at the aforementioned method

	expectedURL := url.URL{
		Scheme: "http",
		Host:   request.Host,
		Path:   request.RequestURI,
	}

I changed it to "https" and it works like a charm. As an enhancement, I'd suggest just allowing for both schemes in the url parameter of the JWS header, to allow pebble to be _agnostic_ where it is exactly running. What do you think?

**Comment by cpu** [comment]
@marsangr That sounds good :+1:. The URL scheme should be populated from the request protocol.

**Comment by cpu** [comment]
Hi @marsangr,

Revisiting this issue I realize what I thought would be an acceptable fix (populating the `expectedURL.Scheme` based on the `request.Proto` or `request.TLS` state won't work for the scenario you describe where TLS is terminated by another daemon and Pebble remains running on HTTP.

> I'd suggest just allowing for both schemes in the url parameter of the JWS header

I think this sort of flexibility is the wrong approach - we don't want requests authenticated by a client expecting it was talking to an HTTPS service to be replayable against the same endpoint on HTTP.

I think a better approach is to drop HTTP support and make Pebble operate on HTTPS by default. I've opened an issue (https://github.com/letsencrypt/pebble/issues/63) for a simple implementation using MiniCA. I'm going to close this issue in favour of 63. Thanks!
