### ISSUE TITLE
Current LetsEncrypt API compatibility?

### ISSUE THREAD

**Issue by donspaulding** [letsencrypt/pebble#57]
Hi there,

I see this repository seems geared towards the upcoming ACME RFC spec.  Is there a sister-project (or fork, or branch) of pebble which codifies the behavior of the current ACME-v01 API being hosted for the Let's Encrypt service?

**Comment by cpu** [comment]
Hi @donspaulding,

There isn't a branch or fork of Pebble geared towards the legacy V1 API (as far as I'm aware!). Your best bet for testing against that API is to use [Boulder](https://github.com/letsencrypt/boulder).

**Comment by donspaulding** [comment]
@cpu That's what I wanted to know, thanks!
