### ISSUE TITLE
Only jwk provided but "jwk/kid mutually exclusive" message

### ISSUE THREAD

**Issue by sophie-h** [letsencrypt/pebble#61]
POSTing to new-order with jwk instead of a kid should give an error, but this message is misleading:

```hs
ProblemDetail 
  { problemDetailType = Just urn:ietf:params:acme:error:malformedRequest
  , problemDetailTitle = Nothing
  , problemDetailStatus = Just 400
  , problemDetailDetail = Just "jwk and kid header fields are mutually exclusive."
  , problemDetailInstance = Nothing
  } 
```

Posting this issue since it sounds like something with input checks could be wrong.

**Comment by cpu** [comment]
I agree the error message is misleading. I'll work on a fix. Thanks @sophie-h !

**Comment by cpu** [comment]
@sophie-h I believe #62 will address this problem. Thanks again for reporting!
