### ISSUE TITLE
Challenge update expect "type"

### ISSUE THREAD

**Issue by sophie-h** [letsencrypt/pebble#69]
Pebble says

> Challenge update was type , existing challenge is type dns-01

The corresponding code is

https://github.com/letsencrypt/pebble/blob/878eac3d373923ff76f9f80423f57a91f1df32c8/wfe/wfe.go#L1107-L1114

But the ACME example just reads

```json
  "payload": base64url({
    "keyAuthorization": "IlirfxKKXA...vb29HhjjLPSggwiE"
  }),
```

– https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#responding-to-challenges

I think pebble shouldn't expect or check a "type" field here.

**Comment by cpu** [comment]
> I think pebble shouldn't expect or check a "type" field here.

@sophie-h Good catch. I agree with you. I think this was some Boulder-cruft that got carried forward incorrectly.

> Challenge update was type , existing challenge is type dns-01
>  fmt.Sprintf("Challenge update was type %s, existing challenge is type %s", 

At the very least it should have been a `%q` instead of a `%s` there to make the error message nicer :-)
