### ISSUE TITLE
Authorizations are not required to be already validated on 'finalize'

### ISSUE THREAD

**Issue by sophie-h** [letsencrypt/pebble#81]
If I am immediately POSTing to "finalize" after I have posted to the challenge "url", pebble says

> Authorization for "localhost" is not status valid

But ACME-09 reads

> Once the client believes it has fulfilled the server’s requirements, it should send a POST request to the order resource’s finalize URL.

This is not "Once the client believes the server has validated …"

Further

> A valid request to finalize an order will return the order to be finalized. The client should begin polling the order
> …
> “pending”: The server does not believe that the client has fulfilled the requirements. Check the “authorizations” array for entries that are still pending.

which suggests, that there might be pending authorizations after POSTing to finalize.

That's why I removed the polling for authorizations in the ACME example. The order should give an overall status after finalization:

https://github.com/ietf-wg-acme/acme/commit/4ac605e53ec654109ce0a30e63080240063c1233#diff-8430e2aa241beb4ac49b252db20d4ee8L668

**Comment by cpu** [comment]
@sophie-h I'm not sure I fully understand this issue. Can you elaborate, maybe including the POST bodies & responses in question?

You say you've posted the order's authorization's challenge URL(s), did that successfully transition the authorizations to state valid?

**Comment by sophie-h** [comment]
First a quick reply. Maybe that's already sufficient for clarification.

> You say you've posted the order's authorization's challenge URL(s), did that successfully transition the authorizations to state valid?

Most likely not, because validation is deferred. I think the main question is: Can I finalize before all authorizations are valid?

**Comment by cpu** [comment]
Hi @sophie-h,

I only just saw that you posted a message related to this to the ACME WG mailing list as well. I'm a bit behind on my Inbox after the holidays but will try to get to the ACME WG in the next day or so.

> Most likely not, because validation is deferred. I think the main question is: Can I finalize before all authorizations are valid?

My expectation was that clients should only finalize when the authorizations in the order are all status = valid.

**Comment by sophie-h** [comment]
Hey @cpu,

> My expectation was that clients should only finalize when the authorizations in the order are all status = valid.

If think this was even the whole point of finalization.  So this seems to be a matter of clarification in the draft.

**Comment by cpu** [comment]
I think the hang-up from this issue is addressed cleanly by the Order "ready" state from https://github.com/letsencrypt/pebble/issues/98. I'm going to close this issue in favour of #98. draft-10+ makes it clear that the order is status "ready" when all of the authorizations are status "valid" and that only status "ready" orders should be finalized.

Thanks!
