### ISSUE TITLE
Implement order "ready" state

### ISSUE THREAD

**Issue by cpu** [letsencrypt/pebble#98]
Per https://tools.ietf.org/html/draft-ietf-acme-acme-10#section-7.1.6 

> Once all of the authorizations listed in the order object are in the "valid" state, the order transitions to the "ready" state.

**Comment by felixfontein** [comment]
Isn't this about the change described in https://community.letsencrypt.org/t/acmev2-order-ready-status/62866? If yes, is there a reason this issue is still open?

**Comment by cpu** [comment]
@felixfontein No reason except that I forgot to close it! Thanks for the ping.
